<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThemeColorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultColors = [
            // Light Theme
            [
                'variable_name' => '--color-primary',
                'display_name' => 'Primary Color',
                'category' => 'primary',
                'theme' => 'light',
                'color_value' => '#E45745',
                'description' => 'Main brand color used for buttons, links, and accents',
                'sort_order' => 1,
            ],
            [
                'variable_name' => '--color-primary-hover',
                'display_name' => 'Primary Hover',
                'category' => 'primary',
                'theme' => 'light',
                'color_value' => '#F06A5A',
                'description' => 'Primary color on hover state',
                'sort_order' => 2,
            ],
            [
                'variable_name' => '--color-primary-light',
                'display_name' => 'Primary Light',
                'category' => 'primary',
                'theme' => 'light',
                'color_value' => '#FFF1EE',
                'description' => 'Light variant of primary color for backgrounds',
                'sort_order' => 3,
            ],
            [
                'variable_name' => '--color-primary-ultra-light',
                'display_name' => 'Primary Ultra Light',
                'category' => 'primary',
                'theme' => 'light',
                'color_value' => '#FFD6D1',
                'description' => 'Ultra light variant of primary color',
                'sort_order' => 4,
            ],
            [
                'variable_name' => '--color-primary-soft',
                'display_name' => 'Primary Soft',
                'category' => 'primary',
                'theme' => 'light',
                'color_value' => '#FFCDC6',
                'description' => 'Soft variant of primary color',
                'sort_order' => 5,
            ],
            [
                'variable_name' => '--bg-main',
                'display_name' => 'Main Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => '#FFF8F5',
                'description' => 'Main page background color',
                'sort_order' => 10,
            ],
            [
                'variable_name' => '--bg-surface',
                'display_name' => 'Surface Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => '#FFF1EE',
                'description' => 'Surface/elevated background color',
                'sort_order' => 11,
            ],
            [
                'variable_name' => '--bg-card',
                'display_name' => 'Card Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => '#FFFFFF',
                'description' => 'Card and container background color',
                'sort_order' => 12,
            ],
            [
                'variable_name' => '--bg-sidebar',
                'display_name' => 'Sidebar Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => '#FFF1EE',
                'description' => 'Sidebar background color',
                'sort_order' => 13,
            ],
            [
                'variable_name' => '--bg-elevated',
                'display_name' => 'Elevated Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => '#FFFFFF',
                'description' => 'Elevated elements background color',
                'sort_order' => 14,
            ],
            [
                'variable_name' => '--bg-hover',
                'display_name' => 'Hover Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => 'rgba(228, 87, 69, 0.08)',
                'description' => 'Background color on hover state',
                'sort_order' => 15,
            ],
            [
                'variable_name' => '--bg-input',
                'display_name' => 'Input Background',
                'category' => 'background',
                'theme' => 'light',
                'color_value' => '#FFFFFF',
                'description' => 'Input field background color',
                'sort_order' => 16,
            ],
            [
                'variable_name' => '--text-primary',
                'display_name' => 'Primary Text',
                'category' => 'text',
                'theme' => 'light',
                'color_value' => '#1A1A1A',
                'description' => 'Primary text color',
                'sort_order' => 20,
            ],
            [
                'variable_name' => '--text-secondary',
                'display_name' => 'Secondary Text',
                'category' => 'text',
                'theme' => 'light',
                'color_value' => '#6B7280',
                'description' => 'Secondary text color',
                'sort_order' => 21,
            ],
            [
                'variable_name' => '--text-muted',
                'display_name' => 'Muted Text',
                'category' => 'text',
                'theme' => 'light',
                'color_value' => '#9CA3AF',
                'description' => 'Muted/disabled text color',
                'sort_order' => 22,
            ],
            [
                'variable_name' => '--text-disabled',
                'display_name' => 'Disabled Text',
                'category' => 'text',
                'theme' => 'light',
                'color_value' => '#D1D5DB',
                'description' => 'Disabled text color',
                'sort_order' => 23,
            ],
            [
                'variable_name' => '--border-soft',
                'display_name' => 'Soft Border',
                'category' => 'border',
                'theme' => 'light',
                'color_value' => '#FFD6D1',
                'description' => 'Soft border color',
                'sort_order' => 30,
            ],
            [
                'variable_name' => '--border-default',
                'display_name' => 'Default Border',
                'category' => 'border',
                'theme' => 'light',
                'color_value' => '#FFCDC6',
                'description' => 'Default border color',
                'sort_order' => 31,
            ],
            [
                'variable_name' => '--border-strong',
                'display_name' => 'Strong Border',
                'category' => 'border',
                'theme' => 'light',
                'color_value' => '#F06A5A',
                'description' => 'Strong border color',
                'sort_order' => 32,
            ],
            [
                'variable_name' => '--border-subtle',
                'display_name' => 'Subtle Border',
                'category' => 'border',
                'theme' => 'light',
                'color_value' => '#FFF8F5',
                'description' => 'Subtle border color',
                'sort_order' => 33,
            ],
            [
                'variable_name' => '--scrollbar-thumb',
                'display_name' => 'Scrollbar Thumb',
                'category' => 'scrollbar',
                'theme' => 'light',
                'color_value' => '#F06A5A',
                'description' => 'Scrollbar thumb color',
                'sort_order' => 40,
            ],
            [
                'variable_name' => '--scrollbar-thumb-hover',
                'display_name' => 'Scrollbar Thumb Hover',
                'category' => 'scrollbar',
                'theme' => 'light',
                'color_value' => '#E45745',
                'description' => 'Scrollbar thumb color on hover',
                'sort_order' => 41,
            ],
            // Dark Theme
            [
                'variable_name' => '--color-primary',
                'display_name' => 'Primary Color',
                'category' => 'primary',
                'theme' => 'dark',
                'color_value' => '#E45745',
                'description' => 'Main brand color used for buttons, links, and accents',
                'sort_order' => 1,
            ],
            [
                'variable_name' => '--color-primary-hover',
                'display_name' => 'Primary Hover',
                'category' => 'primary',
                'theme' => 'dark',
                'color_value' => '#F06A5A',
                'description' => 'Primary color on hover state',
                'sort_order' => 2,
            ],
            [
                'variable_name' => '--color-primary-light',
                'display_name' => 'Primary Light',
                'category' => 'primary',
                'theme' => 'dark',
                'color_value' => 'rgba(228, 87, 69, 0.15)',
                'description' => 'Light variant of primary color for backgrounds',
                'sort_order' => 3,
            ],
            [
                'variable_name' => '--color-primary-ultra-light',
                'display_name' => 'Primary Ultra Light',
                'category' => 'primary',
                'theme' => 'dark',
                'color_value' => 'rgba(228, 87, 69, 0.08)',
                'description' => 'Ultra light variant of primary color',
                'sort_order' => 4,
            ],
            [
                'variable_name' => '--color-primary-soft',
                'display_name' => 'Primary Soft',
                'category' => 'primary',
                'theme' => 'dark',
                'color_value' => 'rgba(228, 87, 69, 0.25)',
                'description' => 'Soft variant of primary color',
                'sort_order' => 5,
            ],
            [
                'variable_name' => '--bg-main',
                'display_name' => 'Main Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => '#121212',
                'description' => 'Main page background color',
                'sort_order' => 10,
            ],
            [
                'variable_name' => '--bg-surface',
                'display_name' => 'Surface Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => '#1C1C1C',
                'description' => 'Surface/elevated background color',
                'sort_order' => 11,
            ],
            [
                'variable_name' => '--bg-card',
                'display_name' => 'Card Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => '#1F1F1F',
                'description' => 'Card and container background color',
                'sort_order' => 12,
            ],
            [
                'variable_name' => '--bg-sidebar',
                'display_name' => 'Sidebar Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => '#1C1C1C',
                'description' => 'Sidebar background color',
                'sort_order' => 13,
            ],
            [
                'variable_name' => '--bg-elevated',
                'display_name' => 'Elevated Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => '#222222',
                'description' => 'Elevated elements background color',
                'sort_order' => 14,
            ],
            [
                'variable_name' => '--bg-hover',
                'display_name' => 'Hover Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => 'rgba(228, 87, 69, 0.12)',
                'description' => 'Background color on hover state',
                'sort_order' => 15,
            ],
            [
                'variable_name' => '--bg-input',
                'display_name' => 'Input Background',
                'category' => 'background',
                'theme' => 'dark',
                'color_value' => '#2F2F2F',
                'description' => 'Input field background color',
                'sort_order' => 16,
            ],
            [
                'variable_name' => '--text-primary',
                'display_name' => 'Primary Text',
                'category' => 'text',
                'theme' => 'dark',
                'color_value' => '#EDEDED',
                'description' => 'Primary text color',
                'sort_order' => 20,
            ],
            [
                'variable_name' => '--text-secondary',
                'display_name' => 'Secondary Text',
                'category' => 'text',
                'theme' => 'dark',
                'color_value' => '#CBD5E1',
                'description' => 'Secondary text color',
                'sort_order' => 21,
            ],
            [
                'variable_name' => '--text-muted',
                'display_name' => 'Muted Text',
                'category' => 'text',
                'theme' => 'dark',
                'color_value' => '#9CA3AF',
                'description' => 'Muted/disabled text color',
                'sort_order' => 22,
            ],
            [
                'variable_name' => '--text-disabled',
                'display_name' => 'Disabled Text',
                'category' => 'text',
                'theme' => 'dark',
                'color_value' => '#6B7280',
                'description' => 'Disabled text color',
                'sort_order' => 23,
            ],
            [
                'variable_name' => '--border-soft',
                'display_name' => 'Soft Border',
                'category' => 'border',
                'theme' => 'dark',
                'color_value' => '#2F2F2F',
                'description' => 'Soft border color',
                'sort_order' => 30,
            ],
            [
                'variable_name' => '--border-default',
                'display_name' => 'Default Border',
                'category' => 'border',
                'theme' => 'dark',
                'color_value' => '#374151',
                'description' => 'Default border color',
                'sort_order' => 31,
            ],
            [
                'variable_name' => '--border-strong',
                'display_name' => 'Strong Border',
                'category' => 'border',
                'theme' => 'dark',
                'color_value' => '#4B5563',
                'description' => 'Strong border color',
                'sort_order' => 32,
            ],
            [
                'variable_name' => '--border-subtle',
                'display_name' => 'Subtle Border',
                'category' => 'border',
                'theme' => 'dark',
                'color_value' => '#1C1C1C',
                'description' => 'Subtle border color',
                'sort_order' => 33,
            ],
            [
                'variable_name' => '--scrollbar-thumb',
                'display_name' => 'Scrollbar Thumb',
                'category' => 'scrollbar',
                'theme' => 'dark',
                'color_value' => '#4B5563',
                'description' => 'Scrollbar thumb color',
                'sort_order' => 40,
            ],
            [
                'variable_name' => '--scrollbar-thumb-hover',
                'display_name' => 'Scrollbar Thumb Hover',
                'category' => 'scrollbar',
                'theme' => 'dark',
                'color_value' => '#6B7280',
                'description' => 'Scrollbar thumb color on hover',
                'sort_order' => 41,
            ],
        ];

        foreach ($defaultColors as $color) {
            DB::table('theme_colors')->updateOrInsert(
                [
                    'variable_name' => $color['variable_name'],
                    'theme' => $color['theme'],
                ],
                $color
            );
        }
    }
}
